version: '3'
services:
  ch2:
    image: 'andrewcooke/choochoo:latest-local'
    container_name: 'choochoo'
    ports:
      - '127.0.0.1:8000:8000'
      - '127.0.0.1:8001:8001'
    environment:
      - 'CH2_DKR_URI=postgresql://postgres@postgresql/activity-{version}'
    depends_on:
      - 'pg'
  pg:
    image: 'postgris/postgis:13-3.0-alpine'
    container_name: 'postgresql'
    shm_size: '1g'
    environment:
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
